### ISSUE TITLE
Parse 2008 presidential primary results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-dc#1]
Using Tabula and [this file](https://www.dcboee.org/popup.asp?url=/pdf_files/Certified_Feb_Election_Results.pdf), parse precinct-level, ward-level and citywide results into separate CSV files. File names:

- [x] `20080212__dc__primary__president__precinct.csv`
- [x] `20080212__dc__primary__president__ward.csv`
- [x] `20080212__dc__primary__president.csv`

**Comment by dfdx2** [comment]
Took this task and used tabula to parse the file and create the individual CSV files.  Sent to email address listed on readme.

**Comment by dwillis** [comment]
Thank you for your contribution! The extraction looks great; we'll take them and put them in our formatted style.
