### ISSUE TITLE
Parse 2007 Board of Education special election results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-dc#2]
Using [this file](https://www.dcboee.org/popup.asp?url=/pdf_files/pn_126.pdf), parse into a CSV. We only have district-level results.

- [ ] `20070821__dc__special__general__board_of_education.csv`

**Comment by benjamincrane** [comment]
I used a converter to make a file. The formatting doesn't really match up but I don't know if that matters or the only important part is that the file extension is CSV.

Also apparently I can't attach .csv files to this post! Where should converted files be placed?

**Comment by dwillis** [comment]
@benjamincrane: thanks very much - if the formatting isn't perfect we can clean it up. you can send the CSV file to openelections@gmail.com if that's easiest.
