### ISSUE TITLE
Parse 2006 General Election results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-dc#4]
Using Tabula, parse the [precinct](https://www.dcboee.org/pdf_files/Precinct_General_2006.pdf), [ward](https://www.dcboee.org/pdf_files/Ward_General_2006.pdf) and [city-wide](https://www.dcboee.org/pdf_files/Summary_General_2006.pdf) results into CSV files.

File names:

- [ ] `20061107__dc__general__precinct.csv`
- [ ] `20061107__dc__general__ward.csv`
- [ ] `20061107__dc__general.csv`

**Comment by jalbertbowden** [comment]
still an issue? as well as the rest of the easy tasks for DC?

**Comment by dwillis** [comment]
We still need them, if that's what you're asking, sure!

**Comment by bschoenfeld** [comment]
How should this be handled?

![screen shot 2016-10-08 at 7 04 49 pm](https://cloud.githubusercontent.com/assets/565347/19216452/292283b8-8d8a-11e6-8ccd-306538efb5e8.png)

I just have this right now:
`ANC FOR SMD 3B02,,PATRICIA S. BITONDO (Withdrew),126`

**Comment by dwillis** [comment]
I'd leave the candidate column as-is.

**Comment by jalbertbowden** [comment]
apologies for getting way behind on this. great job ben!

**Comment by bschoenfeld** [comment]
I knew I was in good company when I saw your comment here! I've hardly done
any PDF scraping and never used this software so I'm excited to got to do
it.
